
name: project_blueprint
description: Flutter Project Blueprint.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  timezone: ^0.9.0
  flutter_svg: ^1.1.5
  ionicons: ^0.2.1
  http: ^0.13.5
  http_interceptor: ^1.0.2
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  jbaza:
    git:
      url: https://github.com/Javoh29/Jbaza

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flags/
    - assets/icons/
    - assets/data/
    - fonts/
  
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-Semibold.ttf
          weight: 600
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-Light.ttf
          weight: 200

