name: takk
description: Flutter Project Blueprint.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  timezone: ^0.9.0
  marquee: ^2.2.3
  modal_bottom_sheet: ^2.1.2
  flutter_svg: ^1.1.5
  ionicons: ^0.2.1
  http: ^0.13.5
  path_provider: ^2.0.11
  http_interceptor: ^1.0.2
  flutter_cache_manager: ^3.3.0
  top_snackbar_flutter: ^2.1.1
  geolocator: ^9.0.2
  badges: ^2.0.3
  geocoding: ^2.0.5
  google_maps_flutter: ^2.2.1
  image_picker: ^0.8.4
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  scroll_to_index: ^3.0.1
  intl: ^0.17.0
  url_launcher: ^6.1.6
  carousel_slider: ^4.1.1
  material_floating_search_bar: ^0.3.7
  flutter_local_notifications: ^13.0.0
  package_info_plus: ^3.0.1
  flame_audio: ^1.3.3
  flutter_localizations:
    sdk: flutter
  jbaza:
    git:
      url: https://github.com/Javoh29/Jbaza

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flags/
    - assets/icons/
    - assets/data/
    - assets/audio/
    - fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-Semibold.ttf
          weight: 600
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-Light.ttf
          weight: 200
